/* Generated By:JavaCC: Do not edit this line. ABLexParserConstants.java */
package com.abuilder.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ABLexParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT_START = 8;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT_END = 9;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 10;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 11;
  /** RegularExpression Id. */
  int AB_DEFINE = 13;
  /** RegularExpression Id. */
  int AB_RULE = 14;
  /** RegularExpression Id. */
  int AB_ACTION = 15;
  /** RegularExpression Id. */
  int AB_STATE = 16;
  /** RegularExpression Id. */
  int AB_INSERT_STATE = 17;
  /** RegularExpression Id. */
  int AB_LEX_METH_INIT = 18;
  /** RegularExpression Id. */
  int AB_CURLY_OPEN = 19;
  /** RegularExpression Id. */
  int AB_CURLY_CLOSE = 20;
  /** RegularExpression Id. */
  int AB_ROUND_OPEN = 21;
  /** RegularExpression Id. */
  int AB_ROUND_CLOSE = 22;
  /** RegularExpression Id. */
  int AB_COMMA = 23;
  /** RegularExpression Id. */
  int RX_CURLY_CLOSE = 24;
  /** RegularExpression Id. */
  int RX_ACTION = 25;
  /** RegularExpression Id. */
  int RX_INSERT_DEF = 26;
  /** RegularExpression Id. */
  int RX_BOL_ANCHOR = 27;
  /** RegularExpression Id. */
  int RX_EOL_ANCHOR = 28;
  /** RegularExpression Id. */
  int RX_ROUND_BRQ_OPEN = 29;
  /** RegularExpression Id. */
  int RX_ROUND_BRQ_CLOSE = 30;
  /** RegularExpression Id. */
  int RX_OR = 31;
  /** RegularExpression Id. */
  int RX_DOT = 32;
  /** RegularExpression Id. */
  int RX_POSITIVE_CLOS = 33;
  /** RegularExpression Id. */
  int RX_KLEEN_STAR = 34;
  /** RegularExpression Id. */
  int RX_OPTIONAL_CLOS = 35;
  /** RegularExpression Id. */
  int RX_CC_START = 36;
  /** RegularExpression Id. */
  int RX_CC_START_NEG = 37;
  /** RegularExpression Id. */
  int RX_RNG_START = 38;
  /** RegularExpression Id. */
  int CC_DASH = 39;
  /** RegularExpression Id. */
  int CHAR_CLS_END = 40;
  /** RegularExpression Id. */
  int CC_SEP = 41;
  /** RegularExpression Id. */
  int RANGE_SEP = 42;
  /** RegularExpression Id. */
  int RANGE_END = 43;
  /** RegularExpression Id. */
  int RANGE_NUM = 44;
  /** RegularExpression Id. */
  int ACT_CURLY_OPEN = 45;
  /** RegularExpression Id. */
  int ACT_CURLY_CLOSE = 46;
  /** RegularExpression Id. */
  int AB_LEXER = 47;
  /** RegularExpression Id. */
  int ABSTRACT = 48;
  /** RegularExpression Id. */
  int ASSERT = 49;
  /** RegularExpression Id. */
  int BOOLEAN = 50;
  /** RegularExpression Id. */
  int BREAK = 51;
  /** RegularExpression Id. */
  int BYTE = 52;
  /** RegularExpression Id. */
  int CASE = 53;
  /** RegularExpression Id. */
  int CATCH = 54;
  /** RegularExpression Id. */
  int CHAR = 55;
  /** RegularExpression Id. */
  int CLASS = 56;
  /** RegularExpression Id. */
  int CONST = 57;
  /** RegularExpression Id. */
  int CONTINUE = 58;
  /** RegularExpression Id. */
  int _DEFAULT = 59;
  /** RegularExpression Id. */
  int DO = 60;
  /** RegularExpression Id. */
  int DOUBLE = 61;
  /** RegularExpression Id. */
  int ELSE = 62;
  /** RegularExpression Id. */
  int ENUM = 63;
  /** RegularExpression Id. */
  int EXTENDS = 64;
  /** RegularExpression Id. */
  int FALSE = 65;
  /** RegularExpression Id. */
  int FINAL = 66;
  /** RegularExpression Id. */
  int FINALLY = 67;
  /** RegularExpression Id. */
  int FLOAT = 68;
  /** RegularExpression Id. */
  int FOR = 69;
  /** RegularExpression Id. */
  int GOTO = 70;
  /** RegularExpression Id. */
  int IF = 71;
  /** RegularExpression Id. */
  int IMPLEMENTS = 72;
  /** RegularExpression Id. */
  int IMPORT = 73;
  /** RegularExpression Id. */
  int INSTANCEOF = 74;
  /** RegularExpression Id. */
  int INT = 75;
  /** RegularExpression Id. */
  int INTERFACE = 76;
  /** RegularExpression Id. */
  int LONG = 77;
  /** RegularExpression Id. */
  int NATIVE = 78;
  /** RegularExpression Id. */
  int NEW = 79;
  /** RegularExpression Id. */
  int NULL = 80;
  /** RegularExpression Id. */
  int PACKAGE = 81;
  /** RegularExpression Id. */
  int PRIVATE = 82;
  /** RegularExpression Id. */
  int PROTECTED = 83;
  /** RegularExpression Id. */
  int PUBLIC = 84;
  /** RegularExpression Id. */
  int RETURN = 85;
  /** RegularExpression Id. */
  int SHORT = 86;
  /** RegularExpression Id. */
  int STATIC = 87;
  /** RegularExpression Id. */
  int STRICTFP = 88;
  /** RegularExpression Id. */
  int SUPER = 89;
  /** RegularExpression Id. */
  int SWITCH = 90;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 91;
  /** RegularExpression Id. */
  int THIS = 92;
  /** RegularExpression Id. */
  int THROW = 93;
  /** RegularExpression Id. */
  int THROWS = 94;
  /** RegularExpression Id. */
  int TRANSIENT = 95;
  /** RegularExpression Id. */
  int TRUE = 96;
  /** RegularExpression Id. */
  int TRY = 97;
  /** RegularExpression Id. */
  int VOID = 98;
  /** RegularExpression Id. */
  int VOLATILE = 99;
  /** RegularExpression Id. */
  int WHILE = 100;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 101;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 102;
  /** RegularExpression Id. */
  int HEX_LITERAL = 103;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 104;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 105;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 106;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 107;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 108;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 109;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 110;
  /** RegularExpression Id. */
  int STRING_LITERAL = 111;
  /** RegularExpression Id. */
  int IDENTIFIER = 112;
  /** RegularExpression Id. */
  int LETTER = 113;
  /** RegularExpression Id. */
  int PART_LETTER = 114;
  /** RegularExpression Id. */
  int LPAREN = 115;
  /** RegularExpression Id. */
  int RPAREN = 116;
  /** RegularExpression Id. */
  int LBRACE = 117;
  /** RegularExpression Id. */
  int RBRACE = 118;
  /** RegularExpression Id. */
  int LBRACKET = 119;
  /** RegularExpression Id. */
  int RBRACKET = 120;
  /** RegularExpression Id. */
  int SEMICOLON = 121;
  /** RegularExpression Id. */
  int COMMA = 122;
  /** RegularExpression Id. */
  int DOT = 123;
  /** RegularExpression Id. */
  int AT = 124;
  /** RegularExpression Id. */
  int ASSIGN = 125;
  /** RegularExpression Id. */
  int LT = 126;
  /** RegularExpression Id. */
  int BANG = 127;
  /** RegularExpression Id. */
  int TILDE = 128;
  /** RegularExpression Id. */
  int HOOK = 129;
  /** RegularExpression Id. */
  int COLON = 130;
  /** RegularExpression Id. */
  int EQ = 131;
  /** RegularExpression Id. */
  int LE = 132;
  /** RegularExpression Id. */
  int GE = 133;
  /** RegularExpression Id. */
  int NE = 134;
  /** RegularExpression Id. */
  int SC_OR = 135;
  /** RegularExpression Id. */
  int SC_AND = 136;
  /** RegularExpression Id. */
  int INCR = 137;
  /** RegularExpression Id. */
  int DECR = 138;
  /** RegularExpression Id. */
  int PLUS = 139;
  /** RegularExpression Id. */
  int MINUS = 140;
  /** RegularExpression Id. */
  int STAR = 141;
  /** RegularExpression Id. */
  int SLASH = 142;
  /** RegularExpression Id. */
  int BIT_AND = 143;
  /** RegularExpression Id. */
  int BIT_OR = 144;
  /** RegularExpression Id. */
  int XOR = 145;
  /** RegularExpression Id. */
  int REM = 146;
  /** RegularExpression Id. */
  int LSHIFT = 147;
  /** RegularExpression Id. */
  int PLUSASSIGN = 148;
  /** RegularExpression Id. */
  int MINUSASSIGN = 149;
  /** RegularExpression Id. */
  int STARASSIGN = 150;
  /** RegularExpression Id. */
  int SLASHASSIGN = 151;
  /** RegularExpression Id. */
  int ANDASSIGN = 152;
  /** RegularExpression Id. */
  int ORASSIGN = 153;
  /** RegularExpression Id. */
  int XORASSIGN = 154;
  /** RegularExpression Id. */
  int REMASSIGN = 155;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 156;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 157;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 158;
  /** RegularExpression Id. */
  int ELLIPSIS = 159;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 160;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 161;
  /** RegularExpression Id. */
  int GT = 162;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 164;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int AB_DEFAULT_STATE = 1;
  /** Lexical state. */
  int RX_STATE = 2;
  /** Lexical state. */
  int ACTION_STATE = 3;
  /** Lexical state. */
  int CHR_CLS_STATE = 4;
  /** Lexical state. */
  int RANGE_STATE = 5;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 6;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 7;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 8;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT_START>",
    "\"\\n\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "\"define\"",
    "\"rule\"",
    "\"action\"",
    "\"state\"",
    "\"insert\"",
    "\"init\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"}\"",
    "\"@action\"",
    "\"@insert\"",
    "\"^\"",
    "\"$\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
    "\".\"",
    "\"+\"",
    "\"*\"",
    "\"?\"",
    "\"[\"",
    "\"[^\"",
    "\"{\"",
    "\"-\"",
    "\"]\"",
    "\",\"",
    "\",\"",
    "\"}\"",
    "<RANGE_NUM>",
    "\"{\"",
    "\"}\"",
    "\"@@\"",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
  };

}
